183. Customers Who Never Order

In [1]:
import pandas as pd
import numpy as np

In [2]:
# pandas schema from leetcode 
data = [[1, 'Joe'], [2, 'Henry'], [3, 'Sam'], [4, 'Max']]
customers = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})
data = [[1, 3], [2, 1]]
orders = pd.DataFrame(data, columns=['id', 'customerId']).astype({'id':'Int64', 'customerId':'Int64'})

In [3]:
customers

   id   name
0   1    Joe
1   2  Henry
2   3    Sam
3   4    Max

In [4]:
orders

   id  customerId
0   1           3
1   2           1

## 💡 Intuition

This problem requires a **LEFT JOIN** because the **Customers** table contains information about **all customers**, while the **Orders** table contains information only about customers who have placed an order.

Since our goal is to find customers who **never placed an order**, we need to make the **Customers** table the left table.

### Why LEFT JOIN?

When we perform a `LEFT JOIN`:

* All rows from the **Customers** table are preserved.
* Matching rows from the **Orders** table are included.
* If a customer has no matching order, the columns coming from the **Orders** table will contain `NULL` values.

```sql
SELECT *
FROM Customers c
LEFT JOIN Orders o
ON c.id = o.customerId;
```

### What happens after the JOIN?

| Customer ID | Customer Name | Order ID |
| ----------- | ------------- | -------- |
| 1           | Joe           | NULL     |
| 2           | Henry         | NULL     |
| 3           | Sam           | 1        |
| 4           | Max           | 2        |

Notice that:

* **Sam** and **Max** have matching orders, so their `Order ID` is populated.
* **Joe** and **Henry** do not have matching orders, so the columns coming from the **Orders** table contain `NULL`.

### Key Observation

If `Order ID` is `NULL`, it means that no order exists for that customer.

Therefore, we can identify customers who never ordered anything by filtering rows where:

```sql
o.id IS NULL
```

This works because a `NULL` value in the Orders table indicates that no matching order was found for that customer during the LEFT JOIN.

# PANDAS SOLUTION

In [5]:
def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    merged=customers.merge(orders,left_on="id",right_on="customerId",how="left")
    return merged[merged["id_y"].isna()][["name"]].rename(columns={"name":"Customers"})
find_customers(customers,orders)

  Customers
1     Henry
3       Max